---
- name: This play installs needed tools to provision infrastructure VMs
  hosts: vm_host
  become: true
  tasks:
    - name: Manage packets when distro is 'CentOS'
      block:
        - name: Upgrade all packages
          ansible.builtin.yum:
            name: '*'
            state: latest # noqa package-latest

        - name: Install required packages
          ansible.builtin.yum:
            name: "{{ os_packages.centos }}"
            state: latest # noqa package-latest
          when:
            - ansible_distribution == 'CentOS'

        - name: Install required packages
          ansible.builtin.yum:
            name: "{{ os_packages.fedora }}"
            state: present
          when:
            - ansible_distribution == 'Fedora'
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'

    - name: Manage packets when distro is 'Ubuntu'
      block:
        - name: Upgrade all packages
          ansible.builtin.apt:
            name: '*'
            state: latest # noqa package-latest

        - name: Install required packages
          ansible.builtin.apt:
            name: "{{ os_packages.ubuntu }}"
            state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Download and provision Terraform
      ansible.builtin.unarchive:
        src: "{{ terraform_url }}"
        dest: /usr/bin/
        mode: 0755
        remote_src: true

    - name: Virtualization services are enabled
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true
